var util = require('../../utils/util.js')

Page({
    data: {
        swiperlist2:[{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/jinrong-s1.jpg',
            tittle:'资金监管',
            desc:'签约多家银行做交易资金监管使二手房交易更加公平更加安全，承诺0收费。'
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/jinrong-s2.jpg',
            tittle:'坐标贷',
            desc:'为交易资金需求方量身打造低成本的资金供给方案。'
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/jinrong-s3.jpg',
            tittle:'按揭贷款',
            desc:'资深金融经理一对一服务为您量身打造最适合您的按揭贷款方式。'
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/jinrong-s4.jpg',
            tittle:'抵押贷款',
            desc:'签约多家银行多渠道高额度批量办理，银行绿色通道便捷办理。'
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/jinrong-s5.jpg',
            tittle:'银行理财',
            desc:'资深金融团队为您整理大多数银行的优秀理财产品，为您的空闲资金带来稳健收益。'
        }],
        swiperlist3:[{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/tese_02.png',
            tittle:'一站式办理',
            desc:'经纪公司门店即可一站式办理，无须银行排队。'
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/tese_04.png',
            tittle:'简单快捷',
            desc:'居间托管保证房款安全，证书加密保证账户安全，监管流程全程可查询。'
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/tese_06.png',
            tittle:'简单快捷',
            desc:'办理简单易操作；监管流程简化，房款到帐迅速。'
        }],
        swiperlist4:[{
            icon:'http://m.zuobiao.wang/fuwu/jinrong/images/data_09.png',
            num:'248584',
            desc:'累积用户数量（人）'
        },{
            icon:'http://m.zuobiao.wang/fuwu/jinrong/images/data_14.png',
            num:'483',
            desc:'累积规避风险单量（单）'
        },{
            icon:'http://m.zuobiao.wang/fuwu/jinrong/images/data_20.png',
            num:'614998800',
            desc:'累积规避风险金额（元）'
        }],
        swiperlist5:[{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/anquan_08.png',
            desc1:'实名制认证管理',
            desc2:''
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/anquan_11.png',
            desc1:'不挪用交易资金',
            desc2:''
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/anquan_13.png',
            desc1:'非客户本人',
            desc2:'无法运用房款'
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/anquan_15.png',
            desc1:'双重对账机制',
            desc2:'受银行监管'
        }],
        swiperlist6:[{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/jinrong_51.jpg',
            tittle:'我是买房人',
            desc:'买房子最关心能不能最终过户，房款安不安全，坐标金融办理的时间灵活，地点灵活，需要的材料也简单，过户也更加顺利了。'
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/jinrong_53.jpg',
            tittle:'我是卖房人',
            desc:'不用去银行排队，线上或者APP都能及时查看监管信息，大大节省了我们的时间，坐标金融已经成为我们吸引客户的特色业务！'
        },{
            img:'http://m.zuobiao.wang/fuwu/jinrong/images/jinrong_55.jpg',
            tittle:'我是经纪人',
            desc:'"坐标金融能办银行办不了的业务"，解冻房款更便捷！资金监管让买卖房子更安全，让交易更容易达成，跟客户谈交易更有底气了！'
        }],
        swiperlist7:[
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank1.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank2.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank3.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank4.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank5.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank6.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank7.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank8.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank9.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank10.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank11.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank12.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank13.jpg',
            'http://m.zuobiao.wang/fuwu/jinrong/images/bank14.jpg',
        ]
    }
})